### ISSUE TITLE
Change display of events

### ISSUE THREAD

**Issue by my0sin** [acmumn/website-old#4]
Events occurring first should appear on top.

**Comment by mzhang28** [comment]
no, because this also includes past events. because our website doesn't ues javascript we can't dynamically update the page to remove old events either.

one solution could be to have a cron job running daily to rebuild the site so old ones get archived, but unless we do that the events page will remain static

**Comment by my0sin** [comment]
Or we just delete events as they pass.

**Comment by mzhang28** [comment]
that's too manual of a job and i don't feel comfortable trusting people to do that

**Comment by remexre** [comment]
We want to keep old info on the site, too; the cronjob's not really a bad option.

**Comment by mzhang28** [comment]
we can have an "events archive" page for older events

**Comment by remexre** [comment]
This was resolved in 67ad19573ad38bd6ee5a7ea02af0726268a564b5.
